manifest:
  remotes:
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyr
      revision: v3.5-branch
      import:
        name-allowlist:
          - cmsis
          - hal_nordic
          - hal_stm32
          - mbedtls
          - mcuboot
          - tinycrypt
          - zcbor

  self:
    path: adalight_rgb
